server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#management:
 # tracing:
  #  sampling:
  #    probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: http://host.docker.internal:9002/
          predicates:
            - Path=/department/**
        - id: employee-service
          uri: http://host.docker.internal:9001/
          predicates:
            - Path=/employee/**
